Bostads-AB-Mimer/onecore-leasing

package-lock.json
package.json
src/services/lease-service/adapters/xpand-soap-adapter.ts
src/services/lease-service/index.ts
src/services/lease-service/tests/waitingList.test.ts

Endpoints connected to the xpand soap service. 
* GET for waiting list times 
* POST for adding user to waiting list
https://dev.azure.com/mimeronline/ONECore/_boards/board/t/Uthyrning/Issues/?workitem=1268

feat: 1268 validate that applicant belongs to waiting list

---

package-lock.json
package.json
src/services/lease-service/adapters/listing-adapter.ts
src/services/lease-service/index.ts

typkonverting enligt: https://dev.azure.com/mimeronline/ONECore/_boards/board/t/Uthyrning/Issues/?workitem=1346

feat: 1346 handle case conversion and type mapping for listings and applicants

---

src/services/lease-service/adapters/listing-adapter.ts
src/services/lease-service/index.ts

Updated endpoints and functionality to remove an applicant with validation for the contact performing the action

Feat 1262 Endpoints for mimer.nu

---

migrations/20240513163957_create-offer-table.js

- Adds a table for "offers"
Fixes [1402](https://dev.azure.com/mimeronline/ONECore/_boards/board/t/Uthyrning/Issues/?workitem=1402)

feat: 1402 - Create Offer table

---

.eslintrc
.github/workflows/ci.yml
.github/workflows/lint-and-test.yml
package.json
src/middlewares/error-handler.test.ts
src/services/creditsafe/tests/index.test.ts
src/services/lease-service/adapters/xpand/tenant-lease-adapter.ts
src/services/lease-service/adapters/xpand/xpand-soap-adapter.ts
src/services/lease-service/tests/index.test.ts
src/services/lease-service/tests/offers.test.ts
src/services/lease-service/tests/priority-list-service.test.ts
src/services/lease-service/tests/waiting-list.test.ts

Adds a GH actions file that:
- Runs tests
- Runs linting
- Checks for TS errors
During development i struggled a bit with GH actions but I think it was due to github degraded functionality or something like that.
Anyway there are some other changes to testfiles etc from trying to debug those errors. Mainly removing unneccessary mocks and before/beforeEach declarations.
Fixes [1485](https://dev.azure.com/mimeronline/ONECore/_boards/board/t/Uthyrning/Issues/?workitem=1485)

chore: 1485 - lint and test on PR 

---

src/services/lease-service/adapters/listing-adapter.ts
src/services/lease-service/index.ts
src/services/lease-service/tests/factory.ts
src/services/lease-service/tests/index.test.ts

https://dev.azure.com/mimeronline/ONECore/_boards/board/t/Uthyrning/Issues/?workitem=1489
`getApplicantsByContactCodeAndRentalObjectCode` query was previously not working since Applicant does not have a `RentalObjectCode`.

bug: 1489 applicant cannot re-apply a withdrawn application

---

migrations/20240603124731_increase-offer-selection-snapshot-size.js
package-lock.json
package.json
src/services/lease-service/index.ts

Only change is to parse the incoming request body

feat: 1405 - update applicant status

---

src/services/lease-service/tests/index.test.ts
src/services/lease-service/tests/priority-list-service.test.ts
src/services/lease-service/tests/routes/offers.test.ts
src/services/lease-service/tests/waiting-list.test.ts

https://dev.azure.com/mimeronline/ONECore/_boards/board/t/Dev/Issues/?workitem=1538
minor refactor to get rid of hardcoded onecore mocks.

feat: 1538 refactor tests to use factories

---

src/services/lease-service/adapters/listing-adapter.ts
src/services/lease-service/adapters/offer-adapter.ts
src/services/lease-service/adapters/types.ts
src/services/lease-service/tests/adapters/listing-adapter.test.ts

- Add db entity types for our listing and offer adapters where missing
- Refactor getOffers a bit to reuse existing transform functions
- Assert listing data structure in existing test
Not typing up the xpand queries...

1545 - Add types for DB tables and use them in transform functions

---

package-lock.json
package.json
src/services/lease-service/get-tenant.ts
src/services/lease-service/property-rental-rules-validator.ts
src/services/lease-service/routes/applicants.ts
src/services/lease-service/routes/contacts.ts
src/services/lease-service/routes/listings.ts
src/services/lease-service/tests/routes/applicants.test.ts

- Adds route for getting a tenant
A tenant is something I think is different than a contact. A tenant should be someone with at least one housing contract.

1560 - Apply area and address specific rental property rules when creating applicant in internal portal

---

src/services/lease-service/adapters/listing-adapter.ts
src/services/lease-service/routes/listings.ts
src/services/lease-service/tests/adapters/listing-adapter/delete-listing.test.ts
src/services/lease-service/tests/adapters/listing-adapter/index.test.ts

Adds functionality to remove a listing if:
- There are no other entities referencing the listing

MIM-87: Remove listing

---

src/services/lease-service/adapters/xpand/xpand-soap-adapter.ts
src/services/lease-service/routes/contacts.ts
src/services/lease-service/tests/routes/contacts.test.ts

* SOAP call to xpand to remove waiting list for contact
* endpoint to reset wating lists for a contact

Feat:mim-29 Svara ja 2 Skapa kontrakt och nollställ köer

---

src/services/lease-service/offer-service.ts

* Deny offer now sets Applicant status to OfferDeclined

Fix: mim-140 Wrong applicant status when declined

---

src/services/lease-service/adapters/xpand/tenant-lease-adapter.ts
src/services/lease-service/routes/listings.ts

* changed to left join instead of inner. Works for the user in question

Fix: getContact returns nothing

---

src/services/lease-service/adapters/offer-adapter.ts
src/services/lease-service/offer-service.ts
src/services/lease-service/tests/offer-service.test.ts

* answeredAt is set to current date and time when status is updated to accepted or declined

Fix: Offer Answer sets a timestamp on Offer

---

package-lock.json
package.json
src/services/lease-service/adapters/offer-adapter.ts
src/services/lease-service/adapters/types.ts
src/services/lease-service/tests/adapters/offer-adapter.test.ts
src/services/lease-service/tests/factories/offer-applicant.ts

https://linear.app/mimer-onecore/issue/MIM-152/medarbetarportalen-skall-visa-personnummer-och-kundnummer-for-sokande

MIM-152: show nationalRegistrationNumber and contactCode for applicants

---

src/services/lease-service/routes/listings.ts
src/services/lease-service/tests/routes/listings.test.ts

Return the data from the result, not the result itself

fix: create listing returns adapter result

---

src/services/lease-service/routes/listings.ts
src/services/lease-service/tests/routes/listings.test.ts

https://linear.app/mimer-onecore/issue/MIM-187/create-listing-i-leasing-ska-inte-bara-kolla-om-listing-redan-finns

MIM-187: remove duplicate listing check when creating listing

---

package-lock.json
package.json
src/services/lease-service/adapters/listing-adapter.ts
src/services/lease-service/adapters/offer-adapter.ts
src/services/lease-service/routes/offers.ts
src/services/lease-service/tests/adapters/listing-adapter/get-listings-with-applicants.test.ts
src/services/lease-service/tests/routes/offers.test.ts

https://linear.app/mimer-onecore/issue/MIM-171/fixa-till-befintliga-listings-flikar

MIM-171: Get active offer for listing

---

package-lock.json
package.json
src/services/lease-service/routes/listings.ts
src/services/lease-service/tests/routes/listings.test.ts

https://linear.app/mimer-onecore/issue/MIM-169/lagg-till-listing-status-noapplicants-samt-closed

MIM-169: Update listing status

---

package-lock.json
package.json
src/services/lease-service/adapters/listing-adapter.ts
src/services/lease-service/routes/listings.ts
src/services/lease-service/tests/adapters/listing-adapter/get-listings-with-applicants.test.ts

- Adds filter to getting listings with applicants "needs-republish"

MIM-172: Mark listing as "re-published"

---

src/services/lease-service/adapters/offer-adapter.ts
src/services/lease-service/routes/offers.ts
src/services/lease-service/tests/adapters/offer-adapter.test.ts
src/services/lease-service/tests/routes/offers.test.ts

UTH-1: Update offer sent at

---

package-lock.json
package.json
src/services/lease-service/routes/contacts.ts
src/services/lease-service/tests/routes/contacts.test.ts

- Adds endpoint for fetching application profile by contact code

UTH-21: Get application profile

---

package-lock.json
package.json
src/services/lease-service/adapters/application-profile-adapter.ts
src/services/lease-service/routes/contacts.ts
src/services/lease-service/tests/adapters/application-profile-adapter.test.ts
src/services/lease-service/tests/routes/contacts.test.ts

UTH-24: update application profile

---

migrations/20250121103952_application-profile-housing-reference-expires_at-nullable.js
package-lock.json
package.json
src/services/lease-service/adapters/db-schemas.ts

https://linear.app/mimer-onecore/team/UTH/cycle/active

UTH-173: Housing reference expiresAt should be nullable

---

src/services/lease-service/get-tenant.ts
src/services/lease-service/priority-list-service.ts
src/services/lease-service/tests/priority-list-service.test.ts

Contracts that is about to end or ended is not considered to be active contracts when prioritizing applicants to be eligible for parking space offers

Contracts that is about to end or ended is not considered to be active contracts when prioritizing applicants to be eligible for parking space offers

---

src/services/lease-service/adapters/xpand/tenant-lease-adapter.ts

* The first active address is now returned

Fix:UTH 201 The Wrong Customer Address Is Displayed

---

package-lock.json
package.json
src/services/lease-service/get-tenant.ts
src/services/lease-service/priority-list-service.ts
src/services/lease-service/routes/contacts.ts
src/services/lease-service/tests/factories/tenant.ts
src/services/lease-service/tests/priority-list-service.test.ts
src/services/lease-service/tests/routes/contacts.test.ts

* New flag added for tenants that will tell if they only have a lease with status AboutToEnd and no upcoming lease

Feat:UTH-220 Handle Tenants With Leases That is About to End

---

src/services/lease-service/residential-area-rental-rules-validator.ts
src/services/lease-service/tests/residential-area-rental-rules-validator.test.ts

Gryta (GRY) is a residential area with specific rental rules and has been added to the list

Feat:UTH-226 Add Specific Rental Rules for GRY
